#!/usr/bin/env bash
# ShaktimaanAI Watchdog Script
# Generated by: shkmn service install
# Do not edit manually — regenerate with 'shkmn service install'

set -euo pipefail

PID_FILE="{{PID_FILE}}"
LOG_FILE="{{LOG_FILE}}"
REPO_PATH="{{REPO_PATH}}"
CRASH_FILE="{{CRASH_FILE}}"
MODE="{{MODE}}"

log() {
  echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $1" >> "$LOG_FILE"
}

# ─── Check if process is already alive ──────────────────────────────────────

if [ -f "$PID_FILE" ]; then
  EXISTING_PID=$(cat "$PID_FILE" 2>/dev/null || echo "")
  if [ -n "$EXISTING_PID" ] && kill -0 "$EXISTING_PID" 2>/dev/null; then
    log "Process already running (PID $EXISTING_PID) — exiting watchdog"
    exit 0
  fi
  log "Stale PID file found (PID $EXISTING_PID not running) — cleaning up"
  rm -f "$PID_FILE"
fi

# ─── Crash loop protection ─────────────────────────────────────────────────

MAX_CONSECUTIVE_CRASHES=3
BACKOFF_SECONDS=1800  # 30 minutes

CRASH_COUNT=0
if [ -f "$CRASH_FILE" ]; then
  CRASH_DATA=$(cat "$CRASH_FILE" 2>/dev/null || echo "0 0")
  CRASH_COUNT=$(echo "$CRASH_DATA" | awk '{print $1}')
  LAST_CRASH=$(echo "$CRASH_DATA" | awk '{print $2}')
  NOW=$(date +%s)

  # Reset counter if last crash was more than backoff period ago
  if [ "$LAST_CRASH" -gt 0 ] && [ $((NOW - LAST_CRASH)) -gt $BACKOFF_SECONDS ]; then
    CRASH_COUNT=0
    log "Crash counter reset — last crash was over 30 minutes ago"
  fi

  if [ "$CRASH_COUNT" -ge "$MAX_CONSECUTIVE_CRASHES" ]; then
    log "CRASH LOOP DETECTED: $CRASH_COUNT consecutive crashes — backing off for 30 minutes"
    exit 1
  fi
fi

# ─── Update / Pull ─────────────────────────────────────────────────────────

if [ "$MODE" = "source" ]; then
  log "Source mode: pulling latest and rebuilding"
  cd "$REPO_PATH"

  # Resolve default branch dynamically
  DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "master")
  log "Default branch: $DEFAULT_BRANCH"

  if git pull origin "$DEFAULT_BRANCH" >> "$LOG_FILE" 2>&1; then
    log "Git pull successful"
  else
    log "WARNING: git pull failed — continuing with current version"
  fi

  if npm run build >> "$LOG_FILE" 2>&1; then
    log "Build successful"
  else
    log "ERROR: Build failed — aborting start"
    NOW=$(date +%s)
    echo "$((CRASH_COUNT + 1)) $NOW" > "$CRASH_FILE"
    exit 1
  fi
elif [ "$MODE" = "package" ]; then
  log "Package mode: checking for updates"
  if npm update -g shaktimaanai >> "$LOG_FILE" 2>&1; then
    log "Package update check complete"
  else
    log "WARNING: npm update failed — continuing with current version"
  fi
fi

# ─── Start the pipeline ────────────────────────────────────────────────────

log "Starting shkmn pipeline"
shkmn start >> "$LOG_FILE" 2>&1 &
SHKMN_PID=$!
log "Pipeline started (PID $SHKMN_PID)"

# Wait briefly and check if it's still running
sleep 5
if kill -0 "$SHKMN_PID" 2>/dev/null; then
  # Process survived initial startup — reset crash counter
  echo "0 0" > "$CRASH_FILE"
  log "Startup confirmed — crash counter reset"
else
  # Process died during startup — increment crash counter
  NOW=$(date +%s)
  echo "$((CRASH_COUNT + 1)) $NOW" > "$CRASH_FILE"
  log "ERROR: Process died during startup (crash count: $((CRASH_COUNT + 1)))"
  exit 1
fi
